# Generated by Django 3.2.12 on 2023-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('avilable_quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(max_length=255, upload_to='images/')),
                ('serve_type', models.CharField(choices=[('Breakfast', 'breakfast'), ('Lunch', 'dinner'), ('Dinner', 'dinner')], default='Breakfast', max_length=50)),
            ],
        ),
    ]
